services:
  api:
    build:
      context: api
    env_file:
      - .env
    ports:
      - 3000:3000
    networks:
      - naf-net
  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./data_pg:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - naf-net
  fetcher:
      build:
        context: fetcher
      env_file:
        - .env
      depends_on:
        - postgres
      networks:
        - naf-net
networks:
  naf-net:
